import { VibeCard } from './types';

export const VIBE_CARDS: VibeCard[] = [
  {
    id: 'VIBE_01',
    image_url: '/vibe/london-skyline.jpg',
    alt_text: 'London skyline at night with lights reflecting on the Thames',
    right_tags: ['CITY', 'INTENSIVE', 'FAST_PACED', 'URBAN'],
    left_tags: ['CAMPUS', 'RELAXED', 'TRADITIONAL'],
    sort_order: 1,
    active: true,
  },
  {
    id: 'VIBE_02',
    image_url: '/vibe/oxford-quad.jpg',
    alt_text: 'Historic Oxford college quadrangle with stone archways',
    right_tags: ['CAMPUS', 'TRADITIONAL', 'ACADEMIC', 'HISTORIC'],
    left_tags: ['MODERN', 'URBAN', 'CONTEMPORARY'],
    disposition_nudge: { dimension: 'depth', right_delta: 3, left_delta: -2 },
    sort_order: 2,
    active: true,
  },
  {
    id: 'VIBE_03',
    image_url: '/vibe/group-discussion.jpg',
    alt_text: 'Students engaged in lively group discussion around a table',
    right_tags: ['COLLABORATIVE', 'SEMINARS', 'SOCIAL', 'DISCUSSION'],
    left_tags: ['INDEPENDENT', 'SOLO', 'QUIET'],
    disposition_nudge: { dimension: 'social', right_delta: 4, left_delta: -3 },
    sort_order: 3,
    active: true,
  },
  {
    id: 'VIBE_04',
    image_url: '/vibe/library-desk.jpg',
    alt_text: 'Single desk in a quiet library corner with warm lamp light',
    right_tags: ['INDEPENDENT', 'RESEARCH', 'QUIET', 'FOCUSED'],
    left_tags: ['COLLABORATIVE', 'SOCIAL', 'GROUP'],
    disposition_nudge: { dimension: 'social', right_delta: -3, left_delta: 3 },
    sort_order: 4,
    active: true,
  },
  {
    id: 'VIBE_05',
    image_url: '/vibe/science-lab.jpg',
    alt_text: 'Modern science laboratory with equipment and experiments in progress',
    right_tags: ['STEM_PHYSICAL', 'PRACTICAL', 'LAB', 'HANDS_ON'],
    left_tags: ['THEORETICAL', 'DESK_BASED', 'LECTURES'],
    disposition_nudge: { dimension: 'precision', right_delta: 3, left_delta: -2 },
    sort_order: 5,
    active: true,
  },
  {
    id: 'VIBE_06',
    image_url: '/vibe/courtroom.jpg',
    alt_text: 'Grand courtroom interior with wooden panelling and formal seating',
    right_tags: ['SOCIAL_ANALYTICAL', 'LAW', 'FORMAL', 'STRUCTURED'],
    left_tags: ['CREATIVE', 'INFORMAL', 'FLEXIBLE'],
    sort_order: 6,
    active: true,
  },
  {
    id: 'VIBE_07',
    image_url: '/vibe/art-studio.jpg',
    alt_text: 'Bright art studio with canvases, paints, and works in progress',
    right_tags: ['HUMANITIES_CREATIVE', 'EXPRESSIVE', 'ARTISTIC', 'VISUAL'],
    left_tags: ['ANALYTICAL', 'STRUCTURED', 'TECHNICAL'],
    disposition_nudge: { dimension: 'transfer', right_delta: 3, left_delta: -2 },
    sort_order: 7,
    active: true,
  },
  {
    id: 'VIBE_08',
    image_url: '/vibe/hospital-ward.jpg',
    alt_text: 'Modern hospital ward with medical professionals and patients',
    right_tags: ['STEM_LIFE', 'CARE', 'VOCATIONAL', 'HEALTHCARE'],
    left_tags: ['THEORETICAL', 'ACADEMIC', 'RESEARCH'],
    disposition_nudge: { dimension: 'tolerance', right_delta: 3, left_delta: -2 },
    sort_order: 8,
    active: true,
  },
  {
    id: 'VIBE_09',
    image_url: '/vibe/trading-floor.jpg',
    alt_text: 'Busy trading floor with multiple screens and dynamic atmosphere',
    right_tags: ['SOCIAL_ANALYTICAL', 'BUSINESS', 'COMPETITIVE', 'FINANCE'],
    left_tags: ['ACADEMIC', 'THEORETICAL', 'RELAXED'],
    sort_order: 9,
    active: true,
  },
  {
    id: 'VIBE_10',
    image_url: '/vibe/lecture-hall.jpg',
    alt_text: 'Large lecture theatre with tiered seating and presenter at front',
    right_tags: ['EXAM_HEAVY', 'LECTURES', 'TRADITIONAL', 'LARGE_COHORT'],
    left_tags: ['COURSEWORK_HEAVY', 'SEMINARS', 'INTIMATE'],
    sort_order: 10,
    active: true,
  },
  {
    id: 'VIBE_11',
    image_url: '/vibe/seminar-room.jpg',
    alt_text: 'Intimate seminar room with students in discussion around oval table',
    right_tags: ['COURSEWORK_HEAVY', 'DISCUSSION', 'SEMINARS', 'INTIMATE'],
    left_tags: ['EXAM_HEAVY', 'LECTURES', 'LARGE_COHORT'],
    disposition_nudge: { dimension: 'receptivity', right_delta: 3, left_delta: -2 },
    sort_order: 11,
    active: true,
  },
  {
    id: 'VIBE_12',
    image_url: '/vibe/fieldwork.jpg',
    alt_text: 'Students conducting outdoor fieldwork with equipment and notebooks',
    right_tags: ['APPLIED_VOCATIONAL', 'PRACTICAL', 'FIELDWORK', 'OUTDOOR'],
    left_tags: ['DESK_BASED', 'INDOOR', 'THEORETICAL'],
    disposition_nudge: { dimension: 'tolerance', right_delta: 2, left_delta: -1 },
    sort_order: 12,
    active: true,
  },
];

export function getActiveVibeCards(): VibeCard[] {
  return VIBE_CARDS.filter(c => c.active).sort((a, b) => a.sort_order - b.sort_order);
}